In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import cv2
from proj1_code.part1 import *
from proj1_unit_tests.test_part1 import *

In [2]:
def show_image(image):
    cv2.imshow('image', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

opencv read test

In [3]:
image = load_image('data/1a_dog.bmp')
li_image = np.array([
    [0,1,2],
    [3,4,5],
])
lit_image = np.array([
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11],
])
lito_image = np.array([
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11],
    [12,13,14,15]
])

In [4]:
def conv_test(img, kernel):
    result = np.zeros(img.shape)
    krows, kcols = kernel.shape
    padY = kernel.shape[0] // 2
    padX = kernel.shape[1] // 2
    padded_image = cv2.copyMakeBorder(img, padY, padY, padX, padX, cv2.BORDER_CONSTANT)
    print(padded_image)
    
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            print('position: ', i,j)
            #print(kernel,'\n*')
            print(padded_image[i: i + krows, j: j + kcols], '\n=')
            #print(kernel * padded_image[i: i + krows, j: j + kcols],'\n')

In [5]:
kernel = np.array([[1],[1],[1]])
# print(kernel.shape[0], kernel.shape[0] // 2)
# print(kernel.shape[1], kernel.shape[1] // 2)
#fila, columna = lit_image.shape
conv_test(lit_image, kernel)

[[ 0  0  0  0]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  0  0  0]]
position:  0 0
[[0]
 [0]
 [4]] 
=
position:  0 1
[[0]
 [1]
 [5]] 
=
position:  0 2
[[0]
 [2]
 [6]] 
=
position:  0 3
[[0]
 [3]
 [7]] 
=
position:  1 0
[[0]
 [4]
 [8]] 
=
position:  1 1
[[1]
 [5]
 [9]] 
=
position:  1 2
[[ 2]
 [ 6]
 [10]] 
=
position:  1 3
[[ 3]
 [ 7]
 [11]] 
=
position:  2 0
[[4]
 [8]
 [0]] 
=
position:  2 1
[[5]
 [9]
 [0]] 
=
position:  2 2
[[ 6]
 [10]
 [ 0]] 
=
position:  2 3
[[ 7]
 [11]
 [ 0]] 
=


### Identity filter

In [6]:
filter = np.array(
    [
        [0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]
    ]
)

channel_img = np.array(
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11],
        [12, 13, 14, 15]
    ]
)

img = np.zeros((4, 4, 3), dtype=np.uint8)
img[:, :, 0] = channel_img
img[:, :, 1] = channel_img
img[:, :, 2] = channel_img
filtered_img = my_conv2d_numpy(copy.deepcopy(img), filter)
# filtered_img

### Ones filter

In [7]:
filter = np.array([
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],])

channel_img = np.array([
    [0, 1],
    [2, 3]])

img = np.zeros((2, 2, 3), dtype=np.uint8)
for i in range(3):
    img[:, :, i] = channel_img

filtered_img = my_conv2d_numpy(img, filter)
# filtered_img

### Non square filter

In [8]:
filt = np.array([[1,1,1]])
channel_img = np.array([[0, 1, 3], [4, 5, 6]])
img = np.zeros((2,3,3), dtype=np.uint8)
for i in range(3):
    img[:,:,i] = channel_img

filtered_img = my_conv2d_numpy(img, filt)
filtered_img[:,:,0]

array([[ 1.,  4.,  4.],
       [ 9., 15., 11.]])

In [9]:
gt_filtered_channel_img = np.array([[1, 4, 4],[9, 15, 11]])
gt_filtered_img = np.zeros((2, 3, 3), dtype=np.uint8)
for i in range(3):
    gt_filtered_img[:, :, i] = gt_filtered_channel_img
    
gt_filtered_img

array([[[ 1,  1,  1],
        [ 4,  4,  4],
        [ 4,  4,  4]],

       [[ 9,  9,  9],
        [15, 15, 15],
        [11, 11, 11]]], dtype=uint8)